
const SOCIAL_LOGIN_REQUEST = "SOCIAL_LOGIN_REQUEST";
const SOCIAL_LOGIN_SUCCESS = "SOCIAL_LOGIN_SUCCESS";
const SOCIAL_LOGIN_FAILURE = "SOCIAL_LOGIN_FAILURE";

const REGISTER_REQUEST = "REGISTER_REQUEST";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_FAILURE = "REGISTER_FAILURE";


const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST";
const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
const VERIFY_OTP_FAILURE = "VERIFY_OTP_FAILURE";


const LOGIN_EMAIL_REQUEST = "LOGIN_EMAIL_REQUEST";
const LOGIN_EMAIL_SUCCESS = "LOGIN_EMAIL_SUCCESS";
const LOGIN_EMAIL_FAILURE = "LOGIN_EMAIL_FAILURE";

const USER_LOGOUT = "USER_LOGOUT";

const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

const GET_ARTICLES_REQUEST = "GET_ARTICLES_REQUEST";
const GET_ARTICLES_SUCCESS = "GET_ARTICLES_SUCCESS";
const GET_ARTICLES_FAILURE = "GET_ARTICLES_FAILURE";


const GET_USER_PAYMENT_REQUEST = "GET_USER_PAYMENT_REQUEST";
const GET_USER_PAYMENT_SUCCESS = "GET_USER_PAYMENT_SUCCESS";
const GET_USER_PAYMENT_FAILURE = "GET_USER_PAYMENT_FAILURE";

const GET_HOMEJOURNELS_REQUEST = "GET_HOMEJOURNELS_REQUEST";
const GET_HOMEJOURNELS_SUCCESS = "GET_HOMEJOURNELS_SUCCESS";
const GET_HOMEJOURNELS_FAILURE = "GET_HOMEJOURNELS_FAILURE";

const GET_HOMEVIDEOS_REQUEST = "GET_HOMEVIDEOS_REQUEST";
const GET_HOMEVIDEOS_SUCCESS = "GET_HOMEVIDEOS_SUCCESS";
const GET_HOMEVIDEOS_FAILURE = "GET_HOMEVIDEOS_FAILURE";

const GET_INTERACTION_REQUEST = "GET_INTERACTION_REQUEST";
const GET_INTERACTION_SUCCESS = "GET_INTERACTION_SUCCESS";
const GET_INTERACTION_FAILURE = "GET_INTERACTION_FAILURE";

const GET_TRAININGCOURSES_REQUEST = "GET_TRAININGCOURSES_REQUEST";
const GET_TRAININGCOURSES_SUCCESS = "GET_TRAININGCOURSES_SUCCESS";
const GET_TRAININGCOURSES_FAILURE = "GET_TRAININGCOURSES_FAILURE";

const GET_HOMEBOOKS_REQUEST = "GET_HOMEBOOKS_REQUEST";
const GET_HOMEBOOKS_SUCCESS = "GET_HOMEBOOKS_SUCCESS";
const GET_HOMEBOOKS_FAILURE = "GET_HOMEBOOKS_FAILURE";

const GET_NEWSFEED_REQUEST = "GET_NEWSFEED_REQUEST";
const GET_NEWSFEED_SUCCESS = "GET_NEWSFEED_SUCCESS";
const GET_NEWSFEED_FAILURE = "GET_NEWSFEED_FAILURE";

const GET_SLIDERS_REQUEST = "GET_SLIDERS_REQUEST";
const GET_SLIDERS_SUCCESS = "GET_SLIDERS_SUCCESS";
const GET_SLIDERS_FAILURE = "GET_SLIDERS_FAILURE";

const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";

const SAVE_DATA_REQUEST = "SAVE_DATA_REQUEST";


export const types = {

  SOCIAL_LOGIN_REQUEST,
  SOCIAL_LOGIN_SUCCESS,
  SOCIAL_LOGIN_FAILURE,

  REGISTER_REQUEST,
  REGISTER_SUCCESS,
  REGISTER_FAILURE,

  LOGIN_EMAIL_REQUEST,
  LOGIN_EMAIL_SUCCESS,
  LOGIN_EMAIL_FAILURE,

  USER_LOGOUT,


  VERIFY_OTP_REQUEST,
  VERIFY_OTP_SUCCESS,
  VERIFY_OTP_FAILURE,

  GET_PRODUCTS_REQUEST,
  GET_PRODUCTS_SUCCESS,
  GET_PRODUCTS_FAILURE,

  GET_ARTICLES_REQUEST,
  GET_ARTICLES_SUCCESS,
  GET_ARTICLES_FAILURE,

  GET_USER_PAYMENT_REQUEST,
  GET_USER_PAYMENT_SUCCESS,
  GET_USER_PAYMENT_FAILURE,

  GET_HOMEJOURNELS_REQUEST,
  GET_HOMEJOURNELS_SUCCESS,
  GET_HOMEJOURNELS_FAILURE,

  // homeVideos
  GET_HOMEVIDEOS_REQUEST,
  GET_HOMEVIDEOS_SUCCESS,
  GET_HOMEVIDEOS_FAILURE,

  GET_INTERACTION_REQUEST,
  GET_INTERACTION_SUCCESS,
  GET_INTERACTION_FAILURE,

  GET_TRAININGCOURSES_REQUEST,
  GET_TRAININGCOURSES_SUCCESS,
  GET_TRAININGCOURSES_FAILURE,


  GET_HOMEBOOKS_REQUEST,
  GET_HOMEBOOKS_SUCCESS,
  GET_HOMEBOOKS_FAILURE,

  GET_NEWSFEED_REQUEST,
  GET_NEWSFEED_SUCCESS,
  GET_NEWSFEED_FAILURE,

  GET_SLIDERS_REQUEST,
  GET_SLIDERS_SUCCESS,
  GET_SLIDERS_FAILURE,

  GET_CATEGORIES_REQUEST,
  GET_CATEGORIES_SUCCESS,
  GET_CATEGORIES_FAILURE,


  SAVE_DATA_REQUEST,

}