const USER_REQUEST = "USER_REQUEST";
const USER_SUCCESS = "USER_SUCCESS";
const USER_FAILURE = "USER_FAILURE";

const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

const GET_INSIDE_DETAIL_REQUEST = "GET_INSIDE_DETAIL_REQUEST";
const GET_INSIDE_DETAIL_SUCCESS = "GET_INSIDE_DETAIL_SUCCESS";
const GET_INSIDE_DETAIL_FAILURE = "GET_INSIDE_DETAIL_FAILURE";
export const types = {

  USER_REQUEST,
  USER_SUCCESS,
  USER_FAILURE,

  UPDATE_USER_REQUEST,
  UPDATE_USER_SUCCESS,
  UPDATE_USER_FAILURE,

  GET_INSIDE_DETAIL_REQUEST,
  GET_INSIDE_DETAIL_SUCCESS,
  GET_INSIDE_DETAIL_FAILURE,
  
}