



const GET_ESTABLISHMENT_PRODUCTS_REQUEST = "GET_ESTABLISHMENT_PRODUCTS_REQUEST";
const GET_ESTABLISHMENT_PRODUCTS_SUCCESS = "GET_ESTABLISHMENT_PRODUCTS_SUCCESS";
const GET_ESTABLISHMENT_PRODUCTS_FAILURE = "GET_ESTABLISHMENT_PRODUCTS_FAILURE";

const GET_PRODUCTS_ADDONES_REQUEST = "GET_PRODUCTS_ADDONES_REQUEST";
const GET_PRODUCTS_ADDONES_SUCCESS = "GET_PRODUCTS_ADDONES_SUCCESS";
const GET_PRODUCTS_ADDONES_FAILURE = "GET_PRODUCTS_ADDONES_FAILURE";

const LOCATION_USER_REQUEST = "LOCATION_USER_REQUEST";
const LOCATION_USER_SUCCESS = "LOCATION_USER_SUCCESS";
const LOCATION_USER_FAILURE = "LOCATION_USER_FAILURE";


const ADD_CART_PRODUCTS = "ADD_CART_PRODUCTS";
const ADD_CART_REQUEST = "ADD_CART_REQUEST";

const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";

const ALL_HISTORY_ORDER_REQUEST = "ALL_HISTORY_ORDER_REQUEST";
const ALL_HISTORY_ORDER_SUCCESS = "ALL_HISTORY_ORDER_SUCCESS";
const ALL_HISTORY_ORDER_FAILURE = "ALL_HISTORY_ORDER_FAILURE";

const GET_ORDER_DETAIL_REQUEST = "GET_ORDER_DETAIL_REQUEST";
const GET_ORDER_DETAIL_SUCCESS = "GET_ORDER_DETAIL_SUCCESS";
const GET_ORDER_DETAIL_FAILURE = "GET_ORDER_DETAIL_FAILURE";


const ORDER_TIP_REVIEW_REQUEST = "ORDER_TIP_REVIEW_REQUEST";
const ORDER_TIP_REVIEW_SUCCESS = "ORDER_TIP_REVIEW_SUCCESS";
const ORDER_TIP_REVIEW_FAILURE = "ORDER_TIP_REVIEW_FAILURE";

export const types = {


  GET_ESTABLISHMENT_PRODUCTS_REQUEST,
  GET_ESTABLISHMENT_PRODUCTS_SUCCESS,
  GET_ESTABLISHMENT_PRODUCTS_FAILURE,

  GET_PRODUCTS_ADDONES_REQUEST,
  GET_PRODUCTS_ADDONES_SUCCESS,
  GET_PRODUCTS_ADDONES_FAILURE,

  LOCATION_USER_REQUEST,
  LOCATION_USER_SUCCESS,
  LOCATION_USER_FAILURE,

  ADD_CART_REQUEST,
  ADD_CART_PRODUCTS,

  CREATE_ORDER_REQUEST,
  CREATE_ORDER_SUCCESS,
  CREATE_ORDER_FAILURE,

  ALL_HISTORY_ORDER_REQUEST,
  ALL_HISTORY_ORDER_SUCCESS,
  ALL_HISTORY_ORDER_FAILURE,

  GET_ORDER_DETAIL_REQUEST,
  GET_ORDER_DETAIL_SUCCESS,
  GET_ORDER_DETAIL_FAILURE,

  ORDER_TIP_REVIEW_REQUEST,
  ORDER_TIP_REVIEW_SUCCESS,
  ORDER_TIP_REVIEW_FAILURE,
}